
@api = http://localhost:3000/products



GET {{api}}

###

POST {{api}}
Content-Type: application/json

{
    "name": "Cache-Control",
    "description": "For gaming",
    "quantity": 718

}


###


GET {{api}}/1006


###

DELETE {{api}}/1004


###

GET {{api}}/count


###

PUT {{api}}/1
Content-Type: application/json

{
    "Name": "Acer Demon",
    "Description": "For gaming",
    "Quantity": 12

}